# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.50.0"

default_platform :ios

platform :ios do
    before_all do
        if is_ci?
            setup_jenkins
        end

        cert(
            development: true
        )
    end

    desc "build AvatarKit Demo"
    lane :build do
        tagName = sh("git describe --abbrev=0 --tags")
        sh("git checkout " + tagName)

        cocoapods(
            repo_update: true,
        )

        xcodebuild(
            scheme: "AvatarKit Demo",
            workspace: "AvatarKit Demo.xcworkspace",
            destination: [
                'name=iPhone 6s',
                'generic/platform=iOS',
            ],
        )
    end

    # You can define as many lanes as you want

    after_all do |lane|
        # This block is called, only if the executed lane was successful
    end

    error do |lane, exception|

    end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
